# server port
server:
  port: 8080
  servlet:
    session:
      timeout: 43200m  # 세션 타임아웃을 한 달(30일)로 설정

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://task-hub-db.cv2g6cygedq9.eu-west-2.rds.amazonaws.com:11996/dohe_task_hub?serverTimezone=Europe/London&characterEncoding=UTF-8
    username: admin
    password: ehgpxotmzmgjqmdkagh*89

  # spring data jpa 설정
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

logging:
  time-zone: Europe/London
