# server port
server:
  port: 8080
  servlet:
    session:
      timeout: 10080m  # 세션 타임아웃을 일주일으로 설정

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dohe-task-hub.cv2g6cygedq9.eu-west-2.rds.amazonaws.com:3306/dohe_task_hub?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: adminadmin

  # spring data jpa 설정
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
